name: video_editor_example
description: The example project for the video_editor package.

publish_to: "none" 
version: 3.0.0+1

environment:
  flutter: ">=3.0.0"
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_editor:
    path: ../

  fraction: ^4.1.4
  image_picker: ^0.8.9
  media_kit: ^1.1.10+1
  media_kit_libs_video: ^1.0.4
  media_kit_video: ^1.2.4
  path: ^1.8.2
  ffmpeg_kit_flutter_min: ^5.1.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1